### ISSUE TITLE
make deploy - results in -> ~/go/bin/controller-gen: No such file or directory

### ISSUE THREAD

**Issue by adligo** [grafana/k6-operator#104]
Hi All, 

   I have a issue getting make deploy to work;

macOs 12.2.1 (21D62)

kubectl version --client
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}

go version go1.18 darwin/amd64

GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

{Version:kustomize/v4.5.2 GitCommit:9091919699baf1c5a5bf71b32ca73a993e98088b BuildDate:2022-02-09T23:19:28Z GoOs:darwin GoArch:amd64}

The output looks as follows with some privacy modifications (i.e. -> ~)
...
go: added sigs.k8s.io/yaml v1.2.0
~/go/bin/controller-gen "crd:trivialVersions=true,crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/bin/sh: ~/go/bin/controller-gen: No such file or directory

Please Help, & TIA :)

**Comment by adligo** [comment]
Any good docker images that are known to build correctly ?

**Comment by adligo** [comment]
I guess docker pull grafana/k6

**Comment by adligo** [comment]
Also having this same issue on ubuntu

**Comment by adligo** [comment]
```
go get github.com/llparse/controller-gen
go install github.com/llparse/controller-gen
```

got me to a new error
```
go: added sigs.k8s.io/yaml v1.2.0
~/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
F0318 20:27:24.762765   87169 packages.go:59] Failed loading boilerplate: open k8s.io/kubernetes/hack/boilerplate/boilerplate.go.txt: no such file or directory
make: *** [manifests] Error 255
```

**Comment by adligo** [comment]
Or should that be;
```
go get sigs.k8s.io/controller-tools
go install sigs.k8s.io/controller-tools
```

**Comment by adligo** [comment]
`brew install k6 `

**Comment by muh-nine** [comment]
@adligo did you find a solution to this error? 
```shell
/Users/x/go/bin/controller-gen: No such file or directory
```

**Comment by yorugac** [comment]
Hi @adligo 

Please look into Makefile; when `controller-gen` binary is absent it should be installed on its own:
https://github.com/grafana/k6-operator/blob/57e4b3e684095d31c6f1d1ef1e2c0bdb4a762e0e/Makefile#L111-L124
`make controller-gen` is invoked by `make deploy` but It seems to fail in your case. So it would be useful to debug why exactly it fails. Either way, the commands can be found in Makefile as can be seen in this snippet.

**Comment by adligo** [comment]
Sure you should add the instructions for which controller-gen you need installed (or suggest installing) as part of your dependencies / instructions.  I have tried a few but was still unsucessful.

**Comment by yorugac** [comment]
> I have tried a few but was still unsucessful.

@adligo did the version in Makefile work? First try to follow the existing commands from `make controller-gen` and see what happens. E.g. do you get a failure, what kind of failure and at what step exactly? Without this info, it's not possible to derive a reason for `make deploy` failure.

As for your suggestion, I personally think that at this point Makefile in root directory is verbose enough for those who need to find the version of `controller-gen`: simply because most people don't need to install it by hand. Your case seems to be an exception at the moment, that's why it needs debugging. Of course, if you see how to improve our README, a PR would be welcome :slightly_smiling_face:

**Comment by gyume2021** [comment]
Hi @adligo 
My setting is as follows: 
1. OS: Ubuntu 20.04
2. kubectl version:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
3. go version go1.18 linux/amd64
4. make version: GNU Make 4.2.1 Built for x86_64-pc-linux-gnu
5. controller-gen version: 0.8

First, I set my GOBIN and GOPATH as `~/go/bin` and controller-gen is in `~/go/bin` as well
Next, I removed veriontrivial in CRD_OPTIONS because it is not supported in my controller-gen version, and everything works.

**Comment by taiyow** [comment]
@adligo 
I met same error and solved.

If using go 1.18, `go get` is obsolete and use `go install` instead but k6-operator/Makefile has not changed so.

I installed following two commands manually:
```
go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.3.0
go install sigs.k8s.io/kustomize/kustomize/v4@latest
```
and after that `make deploy` finished successfully.

**Comment by yorugac** [comment]
The suggested fixes are now part of Makefile in `main`. Closing the issue now. Thanks everyone!

**Comment by daduguai** [comment]
> @adligo I met same error and solved.
> 
> If using go 1.18, `go get` is obsolete and use `go install` instead but k6-operator/Makefile has not changed so.
> 
> I installed following two commands manually:
> 
> ```
> go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.3.0
> go install sigs.k8s.io/kustomize/kustomize/v4@latest
> ```
> 
> and after that `make deploy` finished successfully.

I've tried this, but it doesn't work.  The directory "bin/controller-gen" is not created by.
