### ISSUE TITLE
init container

### ISSUE THREAD

**Issue by ranyhb** [grafana/k6-operator#118]
hi,

i searched the crd and code and found out that the operator dosent have an option for an "initContainer".
i would like to know if you can add it in the next update/release.

**Comment by yorugac** [comment]
Hi @ranyhb, thanks for the issue. Could you please describe your use case too?

**Comment by BarthV** [comment]
Why not allow `k6 run ...` to directly accept url formated files (or archives if possible) ?

**Comment by ranyhb** [comment]
I think you will need to configure the certs and many more other configurations.. 
Imagine also having some teams that use typescript instead of java script, before running the test to need to convert(build) the scripts in order to run them with k6

**Comment by flashmann** [comment]
we would also love to see possibility to use init container to be able to clone git repo with test scripts

**Comment by ranyhb** [comment]
I saw that you are planning to move to helm chart in the next version. In helm you can set hooks and their is a pre-install hook which work similarly to the init container so it can help us solve our problem.
 I would like to know when you are planning to release version 0.0.8.

**Comment by robert-becker-hs** [comment]
Adding to the mix here, init containers would be very useful for us since we are loading our secrets inside an init container and making them available on a mount. So any initialization work would greatly benefit from an init container inside the CRD

**Comment by andrei-trandafir** [comment]
Just trying to revive the conversation around this and show interest as well.

Init containers would be useful for our use-case as well as volume claims may seem a bit tricky for our situation. They'd allow us to mount scripts and data inputs that are stored in a separate bucket into the container. It'd be great to see this added sooner rather than later.

I know there's already a PR for this open, but it hasn't seen activity in over 3 months, so I'd be happy to take over this work to speed things up if possible.
