### ISSUE TITLE
Support for multiple simultaneous tests

### ISSUE THREAD

**Issue by xendren** [grafana/k6-operator#126]
We have the k6-operator running in a k8s cluster.  If TeamA creates a configMap with their load test script and TeamB creates a configMap for their test scripts, can they both apply their k6 resource at the same time to trigger the startup of both sets of load tests?  We are trying to start up another load test while one is running, but the 2nd one is not trying to start.  Looking in the operator log files, it appears that it is still waiting for all of the first test pods to finish.  Is that by design?

**Comment by BarthV** [comment]
At my company we're using kustomize to desbribe our tests suites.
We made it adding an automatic suffix to each deployment to allow such situation.

**Comment by xendren** [comment]
> Hi @xendren, thanks for opening the issue. Yes, it is currently by design. You'll need separate deployments of the operator to support different teams at once.
> 
> This feature may sound simple at first glance but it is rather non-trivial to implement in a reliable manner, e.g. see #108. Also, the roadmap for the operator is in flux so we cannot promise when this feature could be added.

Hey @yorugac, thank you for the response.  I believe operators must be unique per cluster, so that would mean only one test can be ran per cluster at a time.  That is definitely a major limitation or us. 
Thanks again.

**Comment by mugioka** [comment]
> This feature may sound simple at first glance but it is rather non-trivial to implement in a reliable manner

If it is difficult to implement, i want namespace mode k6-operator.
Namespace mode k6-operator is only able to edit k6 CR that is exists in same namespace.

**Comment by yorugac** [comment]
@mugioka you can execute 2+ test runs in different namespaces even now. They just won't be simultaneous.

**Comment by mugioka** [comment]
@yorugac 
> They just won't be simultaneous.

In my environment, I would like to build a multi-tenancy load testing environment. In that case, there may be cases where TeamA and TeamB want to run load tests at the same time, so I thought it would be better to have a single k6 operator that can handle all k6 CRs, or a k6 operator with namespace mode.

**Comment by MohanedSaad** [comment]
Hi @yorugac , we have used the operator in the past and we were able to run tests simultaneously. What has changed to cause this?

**Comment by yorugac** [comment]
Hi @MohanedSaad,
In v0.0.7 we added more complex state processing than before: now operator has initialization and cleanup and also watches for when the test run will finish. It allows new features but obviously, has its drawbacks.
Basically, improving this requires more flexible state processing while maintaining all the features. There's some ongoing work for this so that is in foreseeable future, hopefully. Some related issues: #108, #128

**Comment by kneemaa** [comment]
+1 i would like to only need one operator and allow my teams or CICD to automate running of tests

**Comment by cmergenthaler** [comment]
Is there any update regarding this? We really need to enable multiple simultaneous tests in our loadtest environment

**Comment by cdanmar** [comment]
I wanted to add that simultaneous tests are one of the reasons k6 load testing has been so successful in our organization. The ability to quickly stress test all important services at once enables us to simulate large scale traffic events across multiple services while keeping the testing window small. It also enables our developers to self service their load tests and launch them whenever they want against our environment.

I look forward to this issue being resolved, as we are stuck on the old version since July and I might have to start looking for alternatives soon.
