### ISSUE TITLE
K6 CRD object doesn't progress past `started`

### ISSUE THREAD

**Issue by MarkSRobinson** [grafana/k6-operator#57]
The k6 CRD object does not progress past `stage: started` even after all the downstream jobs have finished.

**Comment by yorugac** [comment]
Hi @MarkSRobinson,
I apologize for the delay in response. Thank you for opening the issue but what you described is not a bug: current implementation of K6 CRD has support for only 2 stages of runner execution, `created` and `started`. Upon re-deploy of the test, the stages loop in this way:
`""` →  `"created"` → `"started"` → `""` →  `"created"` → `"started"` → ... 
Stages will likely be extended with the work done in #79 and #86 but right now this is the expected behavior.

I'm going to close this for now. If there's another case to look into, please feel free to open a new issue.
